language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

env:
  # set environment
  - SHA=$(git rev-parse --short=7 HEAD) FULL_SHA=$(git rev-parse HEAD) HADOLINT_VERSION=v1.17.6 SHELLSHECK_VERSION=v0.4.7 REPO_NAME="postgres-docker-project"

before_install:
  - |
    # get hadolint
    curl -sL -o ${HOME}/hadolint "https://github.com/hadolint/hadolint/releases/download/${HADOLINT_VERSION}/hadolint-$(uname -s)-$(uname -m)"
    chmod +x ${HOME}/hadolint

    # get shellcheck
    wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${SHELLSHECK_VERSION}/shellcheck-${SHELLSHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv
    chmod +x shellcheck-${SHELLSHECK_VERSION}/shellcheck && mv shellcheck-${SHELLSHECK_VERSION}/shellcheck ${HOME}/shellcheck

script:
  - |
    # test hadolint
    find . -maxdepth 3 -type f -iname "*Dockerfile" | xargs ${HOME}/hadolint

    # test shellcheck
    find . -maxdepth 3 -type f -iname "*.sh" | xargs ${HOME}/shellcheck

    # build API image
    docker image build \
      --tag juliocesarmidia/pg-project-api:$SHA \
      --tag juliocesarmidia/pg-project-api:latest \
      ./api

    # run linter for API
    docker container run -it --entrypoint "" juliocesarmidia/pg-project-api:latest yarn run lint

after_success:
  - |
    # log in docker hub
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push images
    docker image push juliocesarmidia/pg-project-api:$SHA
    docker image push juliocesarmidia/pg-project-api:latest

    if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker container run -i --rm \
        --env GITHUB_TOKEN=$GITHUB_TOKEN \
        --env GITHUB_OWNER=julio-cesar-development \
        --env GITHUB_REPO=$REPO_NAME \
        --env GITHUB_COMMENT_TYPE=pr \
        --env GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST \
        --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
        --env GITHUB_COMMENT="build of commit $SHA was successful, LGTM" \
        cloudposse/github-commenter:latest

      echo "{\"commit_id\": \"$FULL_SHA\", \"body\": \"Approved\", \"event\": \"APPROVE\"}" > payload.json

      curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/repos/julio-cesar-development/$REPO_NAME/pulls/$TRAVIS_PULL_REQUEST/reviews \
        -d "@payload.json"
    fi

after_failure:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker container run -i --rm \
        --env GITHUB_TOKEN=$GITHUB_TOKEN \
        --env GITHUB_OWNER=julio-cesar-development \
        --env GITHUB_REPO=$REPO_NAME \
        --env GITHUB_COMMENT_TYPE=pr \
        --env GITHUB_PR_ISSUE_NUMBER=$TRAVIS_PULL_REQUEST \
        --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
        --env GITHUB_COMMENT="build of commit $SHA was not successful" \
        cloudposse/github-commenter:latest

      echo "{\"commit_id\": \"$FULL_SHA\", \"body\": \"Requested changes\", \"event\": \"REQUEST_CHANGES\"}" > payload.json

      curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/repos/julio-cesar-development/$REPO_NAME/pulls/$TRAVIS_PULL_REQUEST/reviews \
        -d "@payload.json"
    fi
