version: "3.4"

services:
  pg-db:
    container_name: pg-db
    restart: on-failure
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
    ports:
      - "35432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-net

  pg-api:
    container_name: pg-api
    restart: on-failure
    build:
      context: ./pq-api
      dockerfile: Dockerfile
      args:
        - API_PORT=40000
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      POSTGRES_HOST: ${POSTGRES_HOST:-pg-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "40000:40000"
    volumes:
      - ./pq-api:/app
      - /app/node_modules
    command: "sh -c 'npm install && npm run dev'"
    networks:
      - pg-net
    depends_on:
      - pg-db

networks:
  pg-net:
    driver: bridge

volumes:
  pg-data:
