version: "3.4"

x-env:
  &default-env
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-postgres_db}

services:
  pg-db:
    container_name: pg-db
    restart: on-failure
    image: postgres:9.6-alpine
    environment:
      <<: *default-env
    ports:
      - "35432:5432"
    volumes:
      - ./pg-init/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
      - pg-data:/var/lib/postgresql/data:rw
    networks:
      pg_project_network:
        ipv4_address: 172.100.10.2
        aliases:
          - pg-svc
          - pg-svc.blackdevs.svc.cluster.local
    domainname: blackdevs.svc.cluster.local
    hostname: pg-svc

  pg-api:
    container_name: pg-api
    restart: on-failure
    build:
      context: ./pg-api
      dockerfile: Dockerfile
      args:
        - API_PORT=40000
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: "sh -c 'yarn install && yarn build && yarn run dev'"
    environment:
      <<: *default-env
      POSTGRES_HOST: ${POSTGRES_HOST:-pg-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      FLUENTD_HOST: ${FLUENTD_HOST:-fluentd-logger}
    ports:
      - "41000:40000"
    volumes:
      - ./pg-api:/app:rw
      - /app/node_modules
    depends_on:
      - pg-db
    networks:
      pg_project_network:
        ipv4_address: 172.100.10.3
        aliases:
          - api-svc
          - api-svc.blackdevs.svc.cluster.local
    domainname: blackdevs.svc.cluster.local
    hostname: api-svc

  fluentd-logger:
    container_name: fluentd-logger
    restart: on-failure
    image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd-config/fluent.conf:/etc/fluent/fluent.conf:rw
    networks:
      pg_project_network:
        ipv4_address: 172.100.10.4
        aliases:
          - fluentd-svc
          - fluentd-svc.blackdevs.svc.cluster.local
    domainname: blackdevs.svc.cluster.local
    hostname: fluentd-svc

networks:
  pg_project_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.100.10.0/24

volumes:
  pg-data:
