apiVersion: v1
kind: Secret
metadata:
  name: env-secrets

type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.postgresPassword | b64enc }}
