apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-data
  namespace: blackdevs

data:
  init.yaml: |
    CREATE SCHEMA IF NOT EXISTS postgres_db;

    \c postgres_db;

    CREATE TABLE users (
      id SERIAL NOT NULL,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(250) NOT NULL,
      active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
    );

    INSERT INTO
      users
    (id, name, email, active, created_at)
      VALUES
    (DEFAULT, 'User 01', 'user01@test.com.br', DEFAULT, DEFAULT),
    (DEFAULT, 'User 02', 'user02@test.com.br', DEFAULT, DEFAULT),
    (DEFAULT, 'User 03', 'user03@test.com.br', DEFAULT, DEFAULT),
    (DEFAULT, 'User 04', 'user04@test.com.br', DEFAULT, DEFAULT),
    (DEFAULT, 'User 05', 'user05@test.com.br', DEFAULT, DEFAULT);

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-statefulset
  namespace: blackdevs

spec:
  replicas: 1
  revisionHistoryLimit: 100

  serviceName: pg-svc

  selector:
    matchLabels:
      app: pg-project-postgres

  template:
    metadata:
      name: pg-statefulset
      labels:
        app: pg-project-postgres

    spec:
      containers:
        - name: pg-db
          image: postgres:9.6-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432
              name: pg-port

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_DB

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.yaml

            - name: data-volume
              mountPath: /var/lib/postgresql/data

            # - name: pg-persistent-storage
            #   mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "128Mi"
              cpu: "256m"

      restartPolicy: Always

      volumes:
        - name: init-volume
          configMap:
            name: pg-data

        - name: data-volume
          emptyDir: {}

        # - name: pg-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: pg-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: blackdevs

spec:
  type: ClusterIP

  selector:
    app: pg-project-postgres

  ports:
    - port: 5432
      targetPort: pg-port
      protocol: TCP
