apiVersion: v1
kind: Secret
metadata:
  name: env-secrets
  namespace: blackdevs

type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXNfZGI=

# kubectl get secret env-secrets
# kubectl describe secret env-secrets
